# Generated by Django 4.2.6 on 2023-10-18 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalstorage',
            options={'ordering': ['validity']},
        ),
        migrations.AddField(
            model_name='contact',
            name='other',
            field=models.CharField(blank=True, help_text='Добавьте заметку', max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='corporation',
            name='other',
            field=models.CharField(blank=True, help_text='Добавьте заметку', max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='other',
            field=models.CharField(blank=True, help_text='Добавьте заметку', max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='fiscalstorage',
            name='other',
            field=models.CharField(blank=True, help_text='Добавьте заметку', max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='legal',
            name='other',
            field=models.CharField(blank=True, help_text='Добавьте заметку', max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='optequip',
            name='other',
            field=models.CharField(blank=True, help_text='Добавьте заметку', max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='printers',
            name='other',
            field=models.CharField(blank=True, help_text='Добавьте заметку', max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='station',
            name='other',
            field=models.CharField(blank=True, help_text='Добавьте заметку', max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telega',
            field=models.CharField(blank=True, help_text='Введите ссылку/логин в Telegram', max_length=30, null=True, verbose_name='Telegram'),
        ),
        migrations.RemoveField(
            model_name='corporation',
            name='establishments',
        ),
        migrations.AlterField(
            model_name='corporation',
            name='iiko_server',
            field=models.CharField(help_text='Введите адрес сервера', max_length=50, verbose_name='Сервер iiko'),
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='establishment',
            name='stations',
        ),
        migrations.AlterField(
            model_name='ofd',
            name='inn',
            field=models.CharField(help_text='Введите ИНН ОФД', max_length=10, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='printers',
            name='sn',
            field=models.CharField(blank=True, help_text='Введите серийный номер принтера (необязательно)', max_length=30, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='rdp',
            name='other',
            field=models.CharField(blank=True, help_text='Добавьте заметку', max_length=200, null=True, verbose_name='Примечание'),
        ),
        migrations.RemoveField(
            model_name='station',
            name='fr',
        ),
        migrations.AddField(
            model_name='corporation',
            name='establishments',
            field=models.ManyToManyField(help_text='Выберите заведения, входящие в это предприятие', to='rezon.establishment', verbose_name='Список точек'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='contact',
            field=models.ManyToManyField(help_text='Выберите контактное лицо', to='rezon.contact', verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='stations',
            field=models.ManyToManyField(help_text='Выберите станции, установленные в этом заведении', to='rezon.station', verbose_name='Станции'),
        ),
        migrations.AddField(
            model_name='station',
            name='fr',
            field=models.ForeignKey(blank=True, help_text='Выберите ФР, если он(они) подключен к этой станции', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rezon.fiscalregistrar', verbose_name='Фискальный регистратор'),
        ),
    ]
