# Generated by Django 4.2.6 on 2023-10-19 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rezon', '0004_modelfiscalregistrar_modelfiscalstorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalregistrar',
            name='model',
            field=models.ForeignKey(help_text='Выберите модель оборудования', on_delete=django.db.models.deletion.DO_NOTHING, to='rezon.modelfiscalregistrar', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='fiscalstorage',
            name='model',
            field=models.ForeignKey(help_text="Введите модель ФН(Например: 'Ин15-3'", on_delete=django.db.models.deletion.DO_NOTHING, to='rezon.modelfiscalstorage', verbose_name='Модель'),
        ),
    ]
