# Generated by Django 4.2.6 on 2023-10-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezon', '0005_alter_fiscalregistrar_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalregistrar',
            name='reg_card',
            field=models.FileField(blank=True, help_text='Прикрепите карточку ККТ', null=True, upload_to='reg_cards', verbose_name='Карточка ККТ'),
        ),
    ]
