# Generated by Django 4.2.6 on 2023-10-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezon', '0006_fiscalregistrar_reg_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(blank=True, help_text='Введите должность', max_length=20, null=True, verbose_name='Должность'),
        ),
    ]
