# Generated by Django 4.2.6 on 2023-10-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezon', '0007_contact_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='fr',
        ),
        migrations.AddField(
            model_name='station',
            name='fr',
            field=models.ManyToManyField(blank=True, help_text='Выберите ФР, если он(они) подключен к этой станции', null=True, to='rezon.fiscalregistrar', verbose_name='Фискальный регистратор'),
        ),
    ]
